### ISSUE TITLE
PRelu always trainable

### ISSUE THREAD

**Issue by jleuschn** [adler-j/adler#1]
Hi, just spotted that in the implementation of `prelu` in _tensorflow/activation.py_ `trainable` is not passed through and instead `tf.get_variable` is always called with `trainable=True`. Seems to me like a bug that's relevant to `leaky_relu`.

**Comment by adler-j** [comment]
That does sound like a bug, would you be able to submit a PR to fix it?

**Comment by jleuschn** [comment]
Sure, did not test, but it seemed simple enough to fix online.

**Comment by adler-j** [comment]
Thanks for helping out! :)
